version: 2.1
orbs:
  docker: circleci/docker@1.7.0
  kubernetes: circleci/kubernetes@1.3.1
  k6io: k6io/test@1.1.0
jobs:
  build:
    docker:
      - image: cimg/go:1.19

    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Set version
          command: |
            make print-version | cat > version.txt
            make print-branch | cat > branch.txt
            make print-rev | cat > rev.txt
            make print-build-user | cat > build-user.txt
      - setup_remote_docker:
          version: 20.10.17
          docker_layer_caching: true
      - run: make docker-run-postgres-dev &
      - run: make docker-run &
  deploy:
    docker:
      - image: cimg/base:stable
    working_directory: ~/repo
    steps:
      - kubernetes/install-kubectl
      - kubernetes/install-kubeconfig:
          kubeconfig: KUBECONFIG_DATA
      - attach_workspace:
          at: ~/
      - setup_remote_docker:
          docker_layer_caching: false
      - docker/configure-docker-credentials-store
      - run: docker login -u i0nw -p $(echo ${DOCKERHUB_PASSWORD})
      - run:  docker build . --build-arg DOCKER_ARG_VERSION=$(cat version.txt) --build-arg DOCKER_ARG_REV=$(cat rev.txt) --build-arg DOCKER_ARG_BRANCH=$(cat branch.txt) --build-arg DOCKER_ARG_BUILD_USER=$(cat build-user.txt) -t i0nw/user-api:latest
      - run: docker tag i0nw/user-api:latest i0nw/user-api:$(cat version.txt)
      - run: |
          docker push i0nw/user-api:latest
          docker push i0nw/user-api:$(cat version.txt)
      - kubernetes/update-container-image:
          container-image-updates: "app=i0nw/user-api:$(cat version.txt)"
          get-rollout-status: true
          resource-name: deployment/user-api

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - k6io/test:
         script: ./test/integration/k6.js
      - deploy:
          requires:
            - k6io/test
